version: '3'

services:
  node-app:
    build: .
    image: node-app
    env_file:
      - .env
    environment:
      PG_USER_NAME: postgres
      PG_PASSWORD: 1234567890
      PG_HOST: postgresdb
      PG_PORT: 5432
      PG_DATABASE: postgres
    ports:
      - '9000:5000'
    depends_on:
      - postgresdb
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network

  postgresdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234567890
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PG_HOST: localhost
    ports:
      - '5432:5432'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
